general:
steps:
  gctsDeploy:
    host: "https://tst.opensap.consarea.com:44300"
    client: "100"
    abapCredentialsId: "SARAT_CREDENTIALS"
    repository: "sarat-krk-sarat_workbench"
    remoteRepositoryURL: "https://github.com/sarat-krk/sarat_workbench"
    role: "SOURCE"
    vSID: "SWB"
    verbose: true
    type: "GIT"
    rollback: false
